# Generated by Django 5.0.4 on 2024-07-03 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='fecha_acordada',
            field=models.DateField(default=datetime.date(2024, 7, 3)),
        ),
    ]
