# Generated by Django 5.0.4 on 2024-07-03 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseniasHabilitadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicante_habilitado', models.BooleanField()),
                ('ofertante_habilitado', models.BooleanField()),
                ('ofertante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertante', to=settings.AUTH_USER_MODEL)),
                ('publicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
