# Generated by Django 5.0.4 on 2024-05-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0002_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='id_publicacion',
            new_name='publicacion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id_respuesta',
        ),
        migrations.AddField(
            model_name='comentario',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='createuser.comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=200),
        ),
    ]
