# Generated by Django 5.0.4 on 2024-07-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0002_reseniashabilitadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='calificacion_promedio',
            field=models.FloatField(default=0),
        ),
    ]
