# Generated by Django 5.0.4 on 2024-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0003_rename_id_publicacion_comentario_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
