# Generated by Django 5.0.4 on 2024-05-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0003_publicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
