# Generated by Django 5.0.4 on 2024-06-14 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0004_alter_intercambio_fecha_acordada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('validez', models.DateField()),
                ('titular', models.CharField(max_length=150)),
                ('cvc', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
