# Generated by Django 5.0.4 on 2024-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0004_comentario_respondido'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='id_ofertante',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
