# Generated by Django 5.0.4 on 2024-06-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0005_tarjeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
