# Generated by Django 5.0.4 on 2024-05-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0005_publicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
