# Generated by Django 5.0.4 on 2024-06-15 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0006_rename_usuario_tarjeta_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='fecha_acordada',
            field=models.DateField(default=datetime.date(2024, 6, 15)),
        ),
    ]
